; University of Florida
; Author: Bohdan Purtell
; Functional 10G TX ingress, buffer, formatter, and XGMII verification.

(library
 (name mac_10g_tx_inline_tests)
 (modules
  tx_testbench
  tx_unit_quickcheck_tests
  tx_expect_tests
  tx_hierarchy_tests)
 (inline_tests
  (flags
   (:standard -source-tree-root .)))
 (libraries
  core
  hardcaml
  hardcaml_verif
  mac_10g_of_hardcaml
  xgmii_of_hardcaml)
 (preprocess
  (pps ppx_hardcaml ppx_jane))
 (lint
  (pps ppx_js_style))
 (flags
  (:standard -w -27-57-33-34-35-40-63-47-26)))
