(library
 (name pcs_tx_scrambler_inline_tests)
 (modules
  pcs_tx_scrambler_testbench
  pcs_tx_scrambler_unit_quickcheck_tests
  pcs_tx_scrambler_expect_tests)
 (inline_tests
  (flags
   (:standard -source-tree-root .)))
 (libraries core hardcaml pcs_of_hardcaml)
 (preprocess
  (pps ppx_hardcaml ppx_jane))
 (lint
  (pps ppx_js_style))
 (flags
  (:standard -w -27-57-33-34-35-40-63-47-26)))
