(library
 (name rx_byte_assembler_inline_tests)
 (modules
  rx_byte_assembler_testbench
  rx_byte_assembler_unit_quickcheck_tests
  rx_byte_assembler_expect_tests)
 (inline_tests)
 (libraries
  core
  hardcaml
  mii_of_hardcaml
  hardcaml_waveterm
  helper_tb_functions
  hardcaml_step_testbench)
 (preprocess
  (pps ppx_hardcaml ppx_jane))
 (flags
  (:standard -w -27-57-33-34-35-40-63-47-26)))
