sh_binary(
    name = "build",
    srcs = ["dune_build.sh"],
    data = [
        "//scripts:with_switch",
    ],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "test",
    srcs = ["dune_test.sh"],
    data = [
        "//scripts:with_switch",
    ],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "fmt",
    srcs = ["dune_fmt.sh"],
    data = [
        "//scripts:with_switch",
    ],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "exec",
    srcs = ["dune_exec.sh"],
    data = [
        "//scripts:with_switch",
    ],
    visibility = ["//visibility:public"],
)
